import Head from 'next/head';
import { Container } from '../styles/Home.module';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vela Atendimento</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon-vela.ico"
        />
      </Head>
      <Container>
        <h1>Hello world!!!</h1>
      </Container>
    </div>
  );
}
